// <auto-generated />
namespace BetterLife.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class mig81 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig81));
        
        string IMigrationMetadata.Id
        {
            get { return "201502011448455_mig81"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
