// <auto-generated />
namespace BetterLife.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class mig12bookdeleted : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig12bookdeleted));
        
        string IMigrationMetadata.Id
        {
            get { return "201502032119593_mig12 book deleted "; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
